In [ ]:
#Basic level of it is :
inputs = [10.1,12.3, 11.1]
weights = [30.1,20.1,18.6]
bias=3


output= inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

760.7


In [ ]:
#Assume real life scenario, where inputs can be from a true input value - ie- Sensors or from other neurons ig
# Modelling a output neuron
inputs = [1,2,3,4]
weights = [0.2,0.8,-0.5,1.0]
bias=3


output= inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(output)

7.3


In [ ]:
# Model say 3 nuerons with 4 inputs: So layer output would not be a single value!!
inputs = [1,2,3,4]
weights = [0.2,0.8,-0.5,1.11]
weights1 = [0.3,0.5,-0.91,0.26]
weights2 = [0.44,0.3,-0.4,1.4]

bias=3
bias1=6.1
bias2=5
output= [inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias, inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias, inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias]
print(output)

[7.74, 2.6100000000000003, 8.44]


In [ ]:
#Now getting our hands dirty, we have:
#We have concept of Activation prograrms- bias is offset or (intercept jaisa for y=mx+c) So 2 different tools (bias and weight) do 2 different works.
inputs = [1,2,3,4]
weights = [[0.2,0.8,-0.5,1.11],[0.3,0.5,-0.91,0.26],[0.44,0.3,-0.4,1.4]]
biases=[3, 6.1, 5]

layer_outputs=[] #Output of current layer
for nw,nb in zip(weights,biases):
    output=0 #Output of given neuron
    for n1,w1 in zip(inputs,nw):
        output+=n1*w1
    output+=nb
    layer_outputs.append(output)
print(layer_outputs)

[7.74, 5.71, 10.44]


In [ ]:
#Single layer ke liye dot product
import numpy as np
#inputs = [1,2,3,4]
#weights = [0.2,0.8,-0.5,1.11]

#outputs= np.dot(weights, inputs)+ bias #On interchanging weights and inputs, we get shape error (I'e error in Matrix Multiplication)
#print(outputs)

inputs = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
weights = [[0.2,0.8,-0.5,1.11],[0.3,0.5,-0.91,0.26],[0.44,0.3,-0.4,1.4]]
# Correcting the shape of weights2 to be compatible with layer1_outputs
weights2 = [[0.22,0.18,-0.25],[05.3,05.5,-03.91],[0.44,0.3,-0.4]] # Adjusted weights2 to have 3 columns
biases=[3, 6.1, 5]
biases2=[3, 6, 0.9]
layer1_outputs= np.dot(inputs,np.array(weights).T)+ biases
layer2_outputs= np.dot(layer1_outputs,np.array(weights2).T)+ biases2 # Now this multiplication is valid
print(layer2_outputs)

[[ 3.1206 37.6066  1.8426]
 [ 2.9054 47.825   2.0722]
 [ 2.6902 58.0434  2.3018]]


In [ ]:
import numpy as np
X=[[1,2,3,2.5],[4,5,6,1.2],[7,8,9,1.45]]
np.random.seed(0)
class Layer_Dense: #We do that as Data passes through, it becomes bigger and bigger till an explosion- Scaling of the dataset.
  def __init__(self, n_inputs, n_neurons):
    self.weights= 0.01* np.random.randn(n_inputs ,n_neurons)#Shaping the weights
    self.biases=np.zeros((1,n_neurons))
  def forward(self, inputs): #Forward Method: takes the inputs
    self.output=np.dot(inputs,self.weights) +self.biases

layer_1= Layer_Dense(4,5)
layer_2= Layer_Dense(5,2)#5 yaha same hai, zaruri for Matrices
layer_1.forward(X)
print(layer_1.output)
layer_2.forward(layer_1.output)
print(layer_2.output)

[[0.01075813 0.10398352 0.02446241 0.0318215  0.01885105]
 [0.03434491 0.16869607 0.07478202 0.0955321  0.11161489]
 [0.06310363 0.25656684 0.12192168 0.16409525 0.19114024]]
[[ 0.00148296 -0.00083976]
 [ 0.00403334 -0.00065392]
 [ 0.006379   -0.0007635 ]]


In [ ]:
import numpy as np
X=[[1,2,3,2.5],[4,5,6,1.2],[7,8,9,1.45]]

inputs =[12,24,48,60,72,13,43,5]
output=[]

for i in inputs:
  output.append(max(0,i)) #Same work
  #if i>0:
    #output.append(i)
  #elif i<=0:
    #output.append(0)
print(output)


[12, 24, 48, 60, 72, 13, 43, 5]


In [ ]:
pip install nnfs

In [ ]:
import numpy as np
import nnfs

nnfs.init()
X=[[1,2,3,2.5],[4,5,6,1.2],[7,8,9,1.45]]
np.random.seed(0)
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights= 0.01* np.random.randn(n_inputs ,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self, inputs):
    self.output=np.dot(inputs,self.weights) +self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

layer_1= Layer_Dense(4,5)
layer_2= Layer_Dense(5,2)

# Convert X to a NumPy array before passing it to the forward method
layer_1.forward(np.array(X))
print(layer_1.output)
layer_2.forward(layer_1.output)
print(layer_2.output)

[[0.01075813 0.10398352 0.02446241 0.0318215  0.01885105]
 [0.03434491 0.16869606 0.07478202 0.09553209 0.11161488]
 [0.06310364 0.25656682 0.12192168 0.16409524 0.19114023]]
[[ 0.00148296 -0.00083976]
 [ 0.00403334 -0.00065392]
 [ 0.006379   -0.0007635 ]]


In [ ]:
pip install nnfs


In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()
X=[[1,2,3,2.5],[4,5,6,1.2],[7,8,9,1.45]]

X,y = spiral_data(100,3)


class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights= 0.01* np.random.randn(n_inputs ,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self, inputs):
    self.output=np.dot(inputs,self.weights) +self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

layer_1= Layer_Dense(2,5) #No of inputs, No of neurons
activation_1= Activation_ReLU()
layer_1.forward(np.array(X))
activation_1.forward(layer_1.output)
print(activation_1.output)

[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 4.6550449e-05 4.5684628e-06]
 [0.0000000e+00 5.9346880e-06 0.0000000e+00 2.0357311e-05 6.1002436e-05]
 ...
 [1.1329151e-02 0.0000000e+00 0.0000000e+00 8.1107961e-03 0.0000000e+00]
 [1.3458835e-02 0.0000000e+00 3.0949395e-03 5.6633754e-03 0.0000000e+00]
 [1.0781791e-02 0.0000000e+00 0.0000000e+00 8.7256189e-03 0.0000000e+00]]


In [ ]:
import math
layer_outputs=[4.8, 1.21, 2.385]

E= math.e
exp_values= []

for output in layer_outputs:
  exp_values.append(E**output)

print(exp_values)

norm_base= sum(exp_values)
norm_values= []
for value in exp_values:
  norm_values.append(value/norm_base)

print(norm_values)
print(sum(norm_values))

[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


In [ ]:
import math
import numpy as np
import nnfs

nnfs.init()

layer_outputs=[[4.8, 1.21, 2.385],[2.11,9.23,7.1],[3.4,5.8,7.1]]
exp_values= np.exp(layer_outputs)
#print(np.sum(layer_outputs, axis=1, keepdims=True)) #For shaping it
norm_values= exp_values/np.sum(exp_values, axis=1, keepdims= True)
print(sum(norm_values))

[0.91506334 1.12793109 0.95700557]


In [ ]:
import math
import numpy as np
import nnfs

nnfs.init()

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights=0.1*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights) + self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

class Activation_Softmax:
  def forward (self,inputs):
    exp_values =np.exp(inputs- np.max(inputs, axis=1,keepdims=True))
    probabilities= exp_values/np.sum(exp_values, axis=1, keepdims=True)
    self.output=probabilities

X,y = spiral_data(samples=100, classes=3)
dense1= Layer_Dense(2,3)
activation1= Activation_ReLU()

dense2=Layer_Dense(3,3)
activation2= Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [ ]:
import math
softmax_output=[0.7,0.1,0.2]
target_output= [1,0,0]

loss =-(math.log(softmax_output[0])*target_output[0]+math.log(softmax_output[1])*target_output[1]+math.log(softmax_output[2])*target_output[2])
print(loss)

0.35667494393873245


In [ ]:
import math
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights=0.1*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights) + self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

class Activation_Softmax:
  def forward (self,inputs):
    exp_values =np.exp(inputs- np.max(inputs, axis=1,keepdims=True))
    probabilities= exp_values/np.sum(exp_values, axis=1, keepdims=True)
    self.output=probabilities

class Loss:
  def calculate(self,output,y):
    sample_losses=self.forward(output,y)
    data_loss=np.mean(sample_losses)
    return data_loss
class Loss_CategoricalCrossentropy(Loss):
  def forward(self,y_pred,y_true):
    samples=len(y_pred)
    y_pred_clipped=np.clip(y_pred,1e-7,1-1e-7)#Setting limits
    if len(y_true.shape)==1:
      correct_confidences= y_pred_clipped[range(samples),y_true]
    elif len(y_true.shape)==2:
      correct_confidences=np.sum(y_pred_clipped*y_true,axis=1)
    negative_log_likelihoods=-np.log(correct_confidences)
    return negative_log_likelihoods



X,y = spiral_data(samples=100, classes=3)
dense1= Layer_Dense(2,3)
activation1= Activation_ReLU()

dense2=Layer_Dense(3,3)
activation2= Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

loss_function= Loss_CategoricalCrossentropy()
loss= loss_function.calculate(activation2.output,y)
print("Loss:",loss)

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
Loss: 1.098445


In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

# Initialize nnfs for consistent data generation and float32 precision
nnfs.init()

# Create dataset: 100 samples per class, 3 classes
X, y = spiral_data(samples=100, classes=3)

# Fully connected (dense) layer
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights with small random values and biases with zeros
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

# ReLU Activation Function
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

# Softmax Activation Function (for output layer)
class Activation_Softmax:
    def forward(self, inputs):
        # Z
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        # Normalize to probabilities
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

# Categorical Cross-Entropy Loss
class Loss_CategoricalCrossentropy:
    def forward(self, y_pred, y_true):
        # Number of samples
        samples = len(y_pred)

        # Clip to prevent log(0)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

        # Probabilities for correct classes
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)

        # Losses
        negative_log_likelihoods = -np.log(correct_confidences)
        return np.mean(negative_log_likelihoods)

# Build the network
dense1 = Layer_Dense(2, 3)          # 2 inputs → 3 neurons
activation1 = Activation_ReLU()     # ReLU after first layer

dense2 = Layer_Dense(3, 3)          # 3 inputs (from dense1) → 3 output neurons
activation2 = Activation_Softmax()  # Softmax for output


dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

#loss
loss_function = Loss_CategoricalCrossentropy()
loss = loss_function.forward(activation2.output, y)

print("First 5 outputs (after Softmax):\n", activation2.output[:5])
print("\nLoss:", loss)


First 5 outputs (after Softmax):
 [[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]

Loss: 1.098445
